def increment(number, by):
    return number + by


print("The increment is =", increment(2, by=1))
# Here the value of increment function is stored in temporary variable which is hidden.....
# To make the code more readable we use keyword argument......
# If someone get confuse by seeing only number parameter then we can make the code more readable by passing keyword....
# argument Here "by = 1" is a keyword argument......
